name = "caffeine"
version = "2021.09.01"
license = "BSD"
author = ["Damian Rouson"]
maintainer = "rouson@lbl.gov"
copyright = "2021 UC Regents"

[dependencies]
assert = {git = "https://github.com/sourceryinstitute/assert", tag = "1.0.0"}

[dev-dependencies]
vegetables = {git = "https://gitlab.com/everythingfunctional/vegetables", tag = "v7.0.2"}
